//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Id.domen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curencies
    {
        public int Id { get; set; }
        public System.DateTime ReqDate { get; set; }
        public string Title { get; set; }
        public string Stitle { get; set; }
        public decimal CurValue { get; set; }
    }
}
