//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Id.domen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public double Value { get; set; }
        public Nullable<int> Currency_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public int PriceType { get; set; }
    
        public virtual Currencies Currencies { get; set; }
        public virtual Products Products { get; set; }
    }
}
