//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Id.domen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMenuItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductMenuItems()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> ProductMenu_Id { get; set; }
        public Nullable<int> Image_Id { get; set; }
        public string Descr { get; set; }
        public bool IsRus { get; set; }
    
        public virtual ProdMenuImages ProdMenuImages { get; set; }
        public virtual ProductMenus ProductMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
