//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Id.domen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telephones
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Numder { get; set; }
        public Nullable<int> DetailsOf_Id { get; set; }
    
        public virtual Details Details { get; set; }
    }
}
