//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Id.domen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string EMail { get; set; }
        public string Phone { get; set; }
        public string Region { get; set; }
        public bool ConfirmEmail { get; set; }
        public bool Block { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> UsrRoles_Id { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual UsrRoles UsrRoles { get; set; }
    }
}
